### ISSUE TITLE
I get 261 bytes long supercut.mp3 which is empty 

### ISSUE THREAD

**Issue by Foolevil** [antiboredom/audiogrep#1]
transcription.txt for audio file seems ok. Where should I start...?

Logs: 

27/02/15 17:08:05,630 apsd[1298]: Unrecognized leaf certificate
27/02/15 17:08:18,832 Console[75959]: setPresentationOptions called with NSApplicationPresentationFullScreen when there is no visible fullscreen window; this call will be ignored.
27/02/15 17:08:38,519 Finder[1299]: FIXME: IOUnserialize has detected a string that is not valid UTF-8, "��{�".
27/02/15 17:08:38,538 Finder[1299]: FIXME: IOUnserialize has detected a string that is not valid UTF-8, "��{�".
27/02/15 17:08:40,214 Finder[1299]: FIXME: IOUnserialize has detected a string that is not valid UTF-8, "��{�".
27/02/15 17:08:41,561 Finder[1299]: FIXME: IOUnserialize has detected a string that is not valid UTF-8, "��{�".

**Comment by antiboredom** [comment]
Can you post the audio file, the transcript and the command line parameters you used?

**Comment by Foolevil** [comment]
Command: python audiogrep.py --input /Users/kimmokivela/Desktop/Audiogreptest/*.mp3 --search 'word'
files are at:
www.turningflowers.fi/post
22.mp3
22.mp3.transcription.txt

**Comment by antiboredom** [comment]
@Foolevil - the problem here is that the word "word" doesn't actually appear in the transcribed text. Try this, for example:
```
python audiogrep.py --input ~/Downloads/Audiogreptest/*.mp3 --search 'father'
```
and let me know if you get any results.

Also, I'll update the code to indicate when it fails to find the search phrase, and if so prevent it from generating an mp3 file.

**Comment by Foolevil** [comment]
-- oops --
