### ISSUE TITLE
Audiogrep complains pocketsphinx isn't installed when it is

### ISSUE THREAD

**Issue by SwartzCr** [antiboredom/audiogrep#20]
I'm trying to run audiogrep inside of a virtualenv, that has pocketshphinx installed, but audiogrep still gives the error that it's not installed :(

It's clearly coming from this line: https://github.com/antiboredom/audiogrep/blob/master/audiogrep/audiogrep.py#L387

Which refers to pocketsphinx_continuous, which pip doesn't know about, but amending it to refer to plain pocketsphinx returns the same error. Giving Popen the path of pocketsphinx.py in the virtualenv's site-packages directory gives `OSError: [Errno 13] Permission denied`

```
(audiogrep):~/Documents/coding/audiogrep$ pip show audiogrep
---
Name: audiogrep
Version: 0.1.2
Location: /home/Documents/coding/audiogrep/lib/python2.7/site-packages
Requires: pydub
(audiogrep):~/Documents/coding/audiogrep$ pip show pocketsphinx
---
Name: pocketsphinx
Version: 0.1.3
Location: /home/Documents/coding/audiogrep/lib/python2.7/site-packages
Requires: 
(audiogrep):~/Documents/coding/audiogrep$ audiogrep --input ../mbmbam01.mp3 --transcribe
Error: Please install pocketsphinx to transcribe files.
```

**Comment by antiboredom** [comment]
huh. can you run ```pocketsphinx_continuous -inmic yes``` just to test that it's installed correctly?

**Comment by SwartzCr** [comment]
hmm so neither `pocketsphinx_continuous` or `pocketshpinx` invocations work :/
Oh I see, I have the library files for it's python package, but not a compiled version of the software, so I obviously can't open it with Popen. Installing it with apt-get has fixed this problem

**Comment by jurassicjordan** [comment]
i'm having the same problem but im on archlinux. none of the version from aur or pacman seem to work
