### ISSUE TITLE
Not able to run audiogrep in Arch Linux

### ISSUE THREAD

**Issue by eerie** [antiboredom/audiogrep#21]
$ audiogrep 
Traceback (most recent call last):
  File "/usr/bin/audiogrep", line 6, in <module>
    audiogrep.main()
AttributeError: module 'audiogrep' has no attribute 'main'

**Comment by vortextemporum** [comment]
Hi eerie, how could you solve the problem?

**Comment by jehoshua7** [comment]
@eerie - I also got the message today. It is coming from /bin/audiogrep

`import audiogrep

if __name__ == '__main__':
    audiogrep.main()`

audiogrep.main()
AttributeError: module 'audiogrep' has no attribute 'main'
