### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by sethwoodworth** [antiboredom/audiogrep#6]
> ./audiogrep.py --input ./Romeo_and_Juliet_Act_1_64kb.mp3 --transcribe
> import: unable to grab mouse `': Resource temporarily unavailable @  error/xwindow.c/XSelectWindow/9199.
> from: can't read /var/mail/pydub
> ./audiogrep.py: 17: ./audiogrep.py: Syntax error: "(" unexpected

According to htop, the command is hanging on `import sys`.  In the audiogrep directory, I have a 23mb file called sys.  While running `--transcribe`, I get a different cursor, and something is trying to grab my mouse input.

I am running debian 8.0 with `ffmpeg` and `pocketsphinx` installed.

This error seems super weird, so I'm happy to dig deeper into the problem.

**Comment by sethwoodworth** [comment]
I also have a file named `subprocess` the same size as `sys` and my original `.mp3` source.

```
-rw-r----- 1 seth seth  22M Mar  6 19:01 Romeo_and_Juliet_Act_1_64kb.mp3
-rw-r--r-- 1 seth seth  23M Mar  6 22:01 subprocess
-rw-r--r-- 1 seth seth  23M Mar  6 22:01 sys
```

**Comment by antiboredom** [comment]
I had forgotten to make it executable. Just fixed it.
